version: 0.0
os: linux
files:
  - source: 
    destination: /root/new_chatapp
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/stop_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/start_server
      timeout: 300
      runas: root

