version: 0.0
os: linux
files:
  - source: /
    destination: /new_chatapp
# hooks:
#   BeforeInstall:
#     - location: scripts/clean.sh
#       timeout: 300
#       runas: root
#   AfterInstall:
#     - location: scripts/supervisorStart.sh
#       timeout: 300
#       runas: root
#   ApplicationStop:
#     - location: scripts/reload_server.sh
#       timeout: 300
#       runas: root
